//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int MId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string EmailAddress { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IpAddress { get; set; }
        public string LoggingDevice { get; set; }
        public string LoggingBrowser { get; set; }
        public string LoggingLocation { get; set; }
    }
}
